import path from "node:path"

export default function(vipen_session) {
	let public_interface = {
		getProjectRoot() {
			return vipen_session.project.root
		},

		getProjectConfig() {
			return vipen_session.project.config
		},

		addWarning(id, message) {
			vipen_session.project.warnings.push({id, message})
		},

		autogenerate: {
			warningComment() {
				return `// Warning: this file was automatically created by vipen vXXXXX
// You will find more information about the specific vipen version used inside the file src/auto/VERSION.txt
// You should commit this file to source control\n`
			}
		},

		distributables: {},

		//
		// used for targets to set target specific data
		//
		target: {
			data: {}
		}
	}

	//
	// files that are added via this interace will be created in
	// "src/auto" folder. This is using the same internal API as the
	// "autogenerate" vipen.config.mjs API.
	//
	// NB: functions that are used to generate autogenerated files
	// always return the source code as a string
	//
	public_interface.autogenerate.addFile = function addAutogeneratedFile(
		file_path, {generator, generator_args}
	) {
		const relative_path = path.join("src", "auto", file_path)
		const absolute_path = path.join(vipen_session.project.root, relative_path)

		vipen_session.files_to_autogenerate.push({
			relative_path,
			absolute_path,
			async generateFileSourceCode() {
				return await generator(public_interface, file_path, ...generator_args)
			}
		})
	}

	//
	//
	//
	public_interface.distributables.addFile = function addDistributionFile(
		file_path, {generator, generator_args}
	) {
		const relative_path = path.join("dist", file_path)
		const absolute_path = path.join(vipen_session.project.root, relative_path)

		vipen_session.distributables.push({
			relative_path,
			absolute_path,
			async generateDistributableFileContents() {
				return await generator(public_interface, file_path, ...generator_args)
			}
		})
	}

	return public_interface
}
