import cleanDistFolder from "./cleanDistFolder.mjs"
import cleanBuildFolder from "./cleanBuildFolder.mjs"
import removeObsoleteAutoGeneratedFiles from "./removeObsoleteAutoGeneratedFiles.mjs"
import createAutoGeneratedFiles from "./createAutoGeneratedFiles.mjs"
import replicateSourceTree from "./replicateSourceTree.mjs"
import preprocessSourceFiles from "./preprocessSourceFiles.mjs"
import createDistributables from "./createDistributables.mjs"

export default [
	cleanDistFolder,
	cleanBuildFolder,
	removeObsoleteAutoGeneratedFiles,
	createAutoGeneratedFiles,
	replicateSourceTree,
	preprocessSourceFiles,
	createDistributables
]
