import path from "node:path"
import {scandir, remove} from "@anio-software/fs"

export default async function(vipen_session) {
	let deleted_entries = []
	const autogenerated_files = vipen_session.files_to_autogenerate.map(file => file.relative_path)
	const auto_dir_entries = await scandir(path.join(vipen_session.project.root, "src", "auto"))
	let directories_on_disk = []

	for (const {type, relative_path} of auto_dir_entries) {
		// handle directories separately
		if (type !== "file") {
			directories_on_disk.push(relative_path)

			continue
		}

		if (!autogenerated_files.includes(`src/auto/${relative_path}`)) {
			await remove(path.join(vipen_session.project.root, "src", "auto", relative_path))
			deleted_entries.push(relative_path)
		}
	}

	for (const directory_on_disk of directories_on_disk) {
		let is_used = false

		for (const autogenerated_file of autogenerated_files) {
			if (autogenerated_file.startsWith(`src/auto/${directory_on_disk}/`)) {
				is_used = true
				break
			}
		}

		if (!is_used) {
			await remove(path.join(vipen_session.project.root, "src", "auto", directory_on_disk))
			deleted_entries.push(directory_on_disk)
		}
	}

	console.log("deleted", deleted_entries.length, "obsolete files/dirs")
}
