import {createRequire} from "node:module"

import createFreshContext from "./lib/createFreshContext.mjs"
import manageAutoGeneratedDirectories from "./lib/manageAutoGeneratedDirectories.mjs"
import fsRemove from "@anio-node-foundation/fs-remove"
import path from "node:path"

async function getTargetModule(project_root, type) {
	if (type.startsWith("js:")) {
		const require = createRequire(path.join(project_root, "index.js"))

		const target_module = await import(require.resolve("@vipen/target-js/vipen-integration"))

		return target_module
	}
}

export default async function(project_root) {
	const target = await getTargetModule(project_root, "js:library")

	let ctx = createFreshContext(project_root)

	await target.initializeTarget(ctx)

	const entries_to_remove = await manageAutoGeneratedDirectories(ctx)

	// old stages in their order:

		// update
		// prep
		// report
		// hk
		// tree
		// scrub
		// gen
		// build
		// test
		// deploy

	for (const entry of entries_to_remove) {
		console.log("removing", entry)

		await fsRemove(path.join(ctx.root, entry))
	}

	for (const f of ctx.files_to_autogenerate) {
		console.log("generating", f.relative_path)

		await f.generate()
	}

	for (const f of ctx.files_to_build) {
		console.log("building", f.relative_path)

		await f.build()
	}
}
